apiVersion: v1
data:
  fluent.conf: |
    <source>
      @type tail
      path /usr/local/apache2/logs/
      pos_file /fluentd/log/httpd-access.log.pos
      tag apache.access
      format apache2
    </source>

    <match **>
      @type elasticsearch
      logstash_format true
      host elasticsearch
      port 9200
      index_name fluentd
      type_name fluentd
    </match>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fluentd-conf
  selfLink: /api/v1/namespaces/default/configmaps/fluentd-conf
