apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kibana
  name: kibana
  selfLink: /api/v1/namespaces/default/services/kibana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
